spring:
  main:
    allow-bean-definition-overriding: true
  application: 
    name: mg-node-user
  data: 
    mongodb: 
      host: 127.0.0.1
      port: 27017
      database: mg
  datasource: 
    password: shineon@1234
    driverclassname: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/rmt_sys_uia_info?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
    username: root
server: 
  port: 121
logging: 
  level: 
    root: info
  file:  ../mg.log/mg.db.user.log
mg:
  version: 20200520
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:81/eureka"
  instance:
    prefer-ip-address: true
mybatis:
  mapperlocations: "classpath:com/mg/node/db/sql/xml/*.xml"

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 10.0.127.235:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070