spring:
  application:
    name: mg-general-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: uauth #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
#            uri: http://www.baidu.com  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://mg-website-uauth #匹配后提供服务的路由地址
          predicates:
            - Path=/api/uauth/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=2

    
server:
  port: 15205

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:15101/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info