server:
  port: 264

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:81/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: mg.auth
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0



