server:
  port: 15201

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:15101/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: mg-general-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MT-GMZ/config
          search-paths: website/{application},node/{application},compose/{application},general/{application}
          username: mmqw1122
          password: Mg12270819



